import { exec as execCallback } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import { assertSkillToolPolicy } from "./policies.js";
import type {
  GraphRunState,
  SkillRuntimePolicy,
  ToolEvent,
  ToolExecutionResult,
  ToolIntent,
} from "../types.js";

const exec = promisify(execCallback);

const SHELL_ALLOWLIST_PREFIXES = ["echo", "pwd", "ls", "cat", "npm run check"];

export interface ToolExecutor {
  executeIntents(state: GraphRunState): Promise<ToolExecutionResult[]>;
}

export interface ToolExecutorOptions {
  projectRoot: string;
  onPreToolUse?: (toolEvent: ToolEvent) => Promise<void>;
  onPostToolUse?: (toolEvent: ToolEvent, result: string) => Promise<void>;
}

export function createToolExecutor(options: ToolExecutorOptions): ToolExecutor {
  return {
    executeIntents: async (state: GraphRunState): Promise<ToolExecutionResult[]> => {
      const results: ToolExecutionResult[] = [];
      const skillMap = new Map<string, SkillRuntimePolicy>(
        state.activeSkillPolicies.map((policy) => [policy.skillId, policy]),
      );
      const callCounts = new Map<string, number>();

      for (const intent of state.plannedToolIntents) {
        const policy = skillMap.get(intent.skillId);
        const nextCount = (callCounts.get(intent.skillId) ?? 0) + 1;
        callCounts.set(intent.skillId, nextCount);

        const toolEvent: ToolEvent = {
          toolName: intent.toolName,
          input: intent.command ?? intent.input,
          skillId: intent.skillId,
          targetPath: intent.targetPath,
          toolCallCount: nextCount,
        };

        try {
          assertSkillToolPolicy(toolEvent, policy);
          if (options.onPreToolUse) {
            await options.onPreToolUse(toolEvent);
          }

          const output = await runIntent(intent, options.projectRoot);

          if (options.onPostToolUse) {
            await options.onPostToolUse(toolEvent, output);
          }

          results.push({
            intentId: intent.id,
            skillId: intent.skillId,
            toolName: intent.toolName,
            status: "ok",
            output,
            timestamp: new Date().toISOString(),
          });
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          results.push({
            intentId: intent.id,
            skillId: intent.skillId,
            toolName: intent.toolName,
            status: message.toLowerCase().includes("policy violation") ? "blocked" : "error",
            output: message,
            timestamp: new Date().toISOString(),
          });
        }
      }

      return results;
    },
  };
}

function inferDefaultPath(input: string): string | undefined {
  const match = input.match(/([A-Za-z0-9_./-]+\.[A-Za-z0-9_-]+)/);
  return match ? match[1] : undefined;
}

function inferUrl(input: string): string | undefined {
  const match = input.match(/https?:\/\/[^\s]+/i);
  return match ? match[0] : undefined;
}

async function runIntent(intent: ToolIntent, projectRoot: string): Promise<string> {
  if (intent.toolName === "shell.run") {
    return runShellCommand(intent.command ?? "echo no-op");
  }

  if (intent.toolName === "file.read") {
    const targetPath = intent.targetPath ?? inferDefaultPath(intent.input);
    if (!targetPath) {
      throw new Error("No file path found for file.read intent");
    }

    const fullPath = join(projectRoot, targetPath);
    const content = await readFile(fullPath, "utf-8");
    return content.slice(0, 1500);
  }

  if (intent.toolName === "file.write") {
    const targetPath = intent.targetPath ?? inferDefaultPath(intent.input);
    if (!targetPath) {
      throw new Error("No file path found for file.write intent");
    }

    if (!intent.input.toLowerCase().includes("allow-write")) {
      return `Dry-run file.write for ${targetPath} (add 'allow-write' to enable actual write)`;
    }

    const fullPath = join(projectRoot, targetPath);
    const content = `Generated by Phase E executor at ${new Date().toISOString()}\n`;
    await writeFile(fullPath, content, "utf-8");
    return `Wrote ${targetPath}`;
  }

  if (intent.toolName === "web.fetch") {
    const url = inferUrl(intent.input);
    if (!url) {
      throw new Error("No URL found for web.fetch intent");
    }

    const response = await fetch(url);
    const text = await response.text();
    return text.slice(0, 1200);
  }

  if (intent.toolName === "reasoning") {
    return `Reasoning summary for request: ${intent.input.slice(0, 200)}`;
  }

  throw new Error(`Unsupported tool: ${intent.toolName}`);
}

async function runShellCommand(command: string): Promise<string> {
  const trimmed = command.trim();
  const allowed = SHELL_ALLOWLIST_PREFIXES.some((prefix) =>
    trimmed === prefix || trimmed.startsWith(`${prefix} `),
  );

  if (!allowed) {
    throw new Error(`Policy violation: shell command not in allowlist: ${trimmed}`);
  }

  const { stdout, stderr } = await exec(trimmed, {
    timeout: 20_000,
    maxBuffer: 1024 * 1024,
  });

  const output = [stdout, stderr].filter(Boolean).join("\n").trim();
  return output || "Shell command completed with no output";
}
